
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: android-file-transfer-linux
  version: '4.0+git' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Simple and reliable MTP client
  description: |
    Simple UI + Fuse wrapper + cli tool for exploring, downloading, uploading
    data from/to your MTP device. Git version has experimental Zune support.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots
  base: core18

  apps:
    android-file-transfer:
      command: bin/desktop-launch android-file-transfer
      desktop: share/applications/android-file-transfer.desktop
      plugs: [x11, network, network-bind, desktop, gsettings, wayland]
      environment:
        # Use GTK3 cursor theme, icon theme and open/save file dialogs.
        QT_QPA_PLATFORMTHEME: gtk3

    aft-mtp-cli:
      command: bin/aft-mtp-cli
    aft-mtp-mount:
      command: bin/aft-mtp-mount

  parts:
    desktop-qt5:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: qt
        plugin: make
        make-parameters: ["FLAVOR=qt5"]
        build-packages:
          - build-essential
          - qtbase5-dev
          - dpkg-dev
        stage-packages:
          - libxkbcommon0
          - ttf-ubuntu-font-family
          - dmz-cursor-theme
          - light-themes
          - adwaita-icon-theme
          - gnome-themes-standard
          - shared-mime-info
          - libqt5gui5
          - libgdk-pixbuf2.0-0
          - libqt5svg5 # for loading icon themes which are svg
          - try: [appmenu-qt5] # not available on core18
          - locales-all
          - xdg-user-dirs
          - fcitx-frontend-qt5

    aftl:
      # See 'snapcraft plugins'
      source: .
      after: [desktop-qt5]
      plugin: cmake

      configflags:
        - -DCMAKE_BUILD_TYPE=Release

      build-packages:
        - qt5-default
        - libfuse-dev
        - libmagic-dev
        - libtag1-dev
        - libssl-dev
        - libreadline-dev
        - pkg-config

      stage-packages:
        - libqt5gui5
        - libqt5widgets5
        - libqt5network5
        - libfuse-dev
        - libmagic-dev
        - libtag1-dev
        - libssl-dev
        - libreadline-dev

  plugs:
    # Support for common GTK themes
    # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
    gtk-3-themes:
      interface: content
      target: $SNAP/data-dir/themes
      default-provider: gtk-common-themes
    icon-themes:
      interface: content
      target: $SNAP/data-dir/icons
      default-provider: gtk-common-themes
    sound-themes:
      interface: content
      target: $SNAP/data-dir/sounds
      default-provider: gtk-common-themes
